dataset_path: /home/xaxi/PycharmProjects/experience-recorder/experience_recorder/dataset.tar
actions_map_path: /home/xaxi/PycharmProjects/experience-trainer/maps
model_save_path: /home/xaxi/PycharmProjects/experience-trainer/models/checkpoints
batch_size: 32
num_workers: 8
epochs: 5000
lr: 0.001

log_dir: /home/xaxi/PycharmProjects/experience-trainer/experience_trainer/lightning_logs